//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.cpp
//  @ Date : 8/6/2021
//  @ Author : 
//
//


#include "Persona.h"

void Persona::comer() {

}

