//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.h
//  @ Date : 8/6/2021
//  @ Author : 
//
//


#if !defined(_PERSONA_H)
#define _PERSONA_H


class Persona {
public:
	void comer();
private:
	String codigo;
	String nombre;
	Int edad;
};

#endif  //_PERSONA_H
