//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Vehiculo.h
//  @ Date : 8/6/2021
//  @ Author : 
//
//


#if !defined(_VEHICULO_H)
#define _VEHICULO_H


class Vehiculo {
public:
    void frenar();
private:
    int phaca;
    int color;
    int marca;
};

#endif  //_VEHICULO_H
