//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Vehiculo.cpp
//  @ Date : 8/6/2021
//  @ Author : 
//
//


#include "Vehiculo.h"

void Vehiculo::frenar() {

}

